cryoAsicGen1:
  enable: True
  ForceWrite: False
  dataWriter:
    enable: True
    dataFile: ''
    open: False
    bufferSize: 0
    maxFileSize: 0
  XilinxKcu1500Pgp3:
    enable: True
  EpixHRGen1Cryo:
    enable: True
    MMCM7Registers:
      enable: False
      CLKOUT0PhaseMux: 0
      CLKOUT0HighTime: 0
      CLKOUT0LowTime: 0
      CLKOUT0Frac: 0
      CLKOUT0FracEn: 0
      CLKOUT0Edge: 0
      CLKOUT0NoCount: 0
      CLKOUT0DelayTime: 0
      CLKOUT1PhaseMux: 0
      CLKOUT1HighTime: 0
      CLKOUT1LowTime: 0
      CLKOUT1Edge: 0
      CLKOUT1NoCount: 0
      CLKOUT1DelayTime: 0
      CLKOUT2PhaseMux: 0
      CLKOUT2HighTime: 0
      CLKOUT2LowTime: 0
      CLKOUT2Edge: 0
      CLKOUT2NoCount: 0
      CLKOUT2DelayTime: 0
      CLKOUT3PhaseMux: 0
      CLKOUT3HighTime: 0
      CLKOUT3LowTime: 0
      CLKOUT3Edge: 0
      CLKOUT3NoCount: 0
      CLKOUT3DelayTime: 0
      CLKOUT4PhaseMux: 0
      CLKOUT4HighTime: 0
      CLKOUT4LowTime: 0
      CLKOUT4Edge: 0
      CLKOUT4NoCount: 0
      CLKOUT4DelayTime: 0
      CLKOUT5PhaseMux: 0
      CLKOUT5HighTime: 0
      CLKOUT5LowTime: 0
      CLKOUT5Edge: 0
      CLKOUT5NoCount: 0
      CLKOUT5DelayTime: 0
      CLKOUT6PhaseMux: 0
      CLKOUT6HighTime: 0
      CLKOUT6LowTime: 0
      CLKOUT6Edge: 0
      CLKOUT6NoCount: 0
      CLKOUT6DelayTime: 0
    MMCMSerdesRegisters:
      enable: True
      CLKOUT0PhaseMux: 0
      CLKOUT0HighTime: 2
      CLKOUT0LowTime: 2
      CLKOUT0Frac: 0
      CLKOUT0FracEn: 0
      CLKOUT0Edge: 0
      CLKOUT0NoCount: 0
      CLKOUT0DelayTime: 0
      CLKOUT1PhaseMux: 0
      CLKOUT1HighTime: 8
      CLKOUT1LowTime: 8
      CLKOUT1Edge: 0
      CLKOUT1NoCount: 0
      CLKOUT1DelayTime: 0
      CLKOUT2PhaseMux: 0
      CLKOUT2HighTime: 14
      CLKOUT2LowTime: 14
      CLKOUT2Edge: 0
      CLKOUT2NoCount: 0
      CLKOUT2DelayTime: 0
      CLKOUT3PhaseMux: 0
      CLKOUT3HighTime: 8
      CLKOUT3LowTime: 8
      CLKOUT3Edge: 0
      CLKOUT3NoCount: 0
      CLKOUT3DelayTime: 0
